        var snowe=document.querySelector(".pianocontainer");
        snowFall.snow(snowe,{flakeCount:50, round:true,minSize:1,maxSize:6});
        var f3 = document.getElementById("f3");
        var f3b = document.getElementById("f3b");
        var g3 = document.getElementById("g3");
        var g3b = document.getElementById("g3b");
        var a3 = document.getElementById("a3");
        var a3b = document.getElementById("a3b");
        var b3 = document.getElementById("b3");
        var c4 = document.getElementById("c4");
        var c4b = document.getElementById("c4b");
        var d4 = document.getElementById("d4");
        var d4b = document.getElementById("d4b");
        var e4 = document.getElementById("e4");
        var f4 = document.getElementById("f4");
        var f4b = document.getElementById("f4b");
        var g4 = document.getElementById("g4");
        var g4b = document.getElementById("g4b");
        var a4 = document.getElementById("a4");
        var a4b = document.getElementById("a4b");
        var b4 = document.getElementById("b4");
        var c5 = document.getElementById("c5");
        var c5b = document.getElementById("c5b");
        var d5 = document.getElementById("d5");
        var d5b = document.getElementById("d5b");
        var e5 = document.getElementById("e5");
        var f5 = document.getElementById("f5");
        var f5b = document.getElementById("f5b");
        var g5 = document.getElementById("g5");
        var g5b = document.getElementById("g5b");
        var a5 = document.getElementById("a5");
        var a5b = document.getElementById("a5b");
        var b5 = document.getElementById("b5");
        var c6 = document.getElementById("c6");
        var c6b = document.getElementById("c6b");
        var d6 = document.getElementById("d6");
        var d6b = document.getElementById("d6b");
        var e6 = document.getElementById("e6");
        var b5a=document.getElementById("b5a");
        var e5a=document.getElementById("e5a");
        var d6a=document.getElementById("d6a");
        var a5a=document.getElementById("a5a");
        var g5ba=document.getElementById("g5ba");
        var f5a=document.getElementById("f5a");
        var b4g4b=document.getElementById("b4g4b")
        var a4f4=document.getElementById("a4f4");
        var a4a=document.getElementById("a4a");       
        var g5a=document.getElementById("g5a");
        var c6a=document.getElementById("c6a");
        function sevdanolmasa(){
        playAudio(g5ba);
        playAudio(e4);
        setTimeout(function() {playAudio(a5)},172);
        setTimeout(function() {playAudio(b4)},345);
        setTimeout(function() {playAudio(g4b)},345);
        setTimeout(function() {playAudio(b5)},345);
        setTimeout(function() {playAudio(b5a)},690);
        setTimeout(function() {playAudio(e4)},690);
        setTimeout(function() {playAudio(b5)},1040);
        setTimeout(function() {playAudio(b4)},1040);
        setTimeout(function() {playAudio(g4b)},1040);
        setTimeout(function() {playAudio(a5)},1390);
        setTimeout(function() {playAudio(d4)},1390);
        setTimeout(function() {playAudio(g5b)},1560);
        setTimeout(function() {playAudio(f5)},1730);
        setTimeout(function() {playAudio(b4)},1730);
        setTimeout(function() {playAudio(g4b)},1730);
        setTimeout(function() {playAudio(e5)},1910);
        setTimeout(function() {playAudio(e5a)},2080);
        setTimeout(function() {playAudio(e4)},2080);
        setTimeout(function() {playAudio(b4)},2430);
        setTimeout(function() {playAudio(g4b)},2430);
        setTimeout(function() {playAudio(e4)},2780);
        setTimeout(function() {playAudio(g5b)},2780);
        setTimeout(function() {playAudio(a5)},2950);
        setTimeout(function() {playAudio(b4)},3130);
        setTimeout(function() {playAudio(g4b)},3130);
        setTimeout(function() {playAudio(b5)},3130);
        setTimeout(function() {playAudio(b5a)},3470);
        setTimeout(function() {playAudio(e4)},3470);
        setTimeout(function() {playAudio(b5)},3820);
        setTimeout(function() {playAudio(b4)},3820);
        setTimeout(function() {playAudio(g4b)},3820);
        setTimeout(function() {playAudio(a5)},4170);
        setTimeout(function() {playAudio(d4)},4170);
        setTimeout(function() {playAudio(g5b)},4340);
        setTimeout(function() {playAudio(f5)},4520);
        setTimeout(function() {playAudio(b4)},4520);
        setTimeout(function() {playAudio(g4b)},4520);
        setTimeout(function() {playAudio(e5)},4690);
        setTimeout(function() {playAudio(e4)},4870);
        setTimeout(function() {playAudio(e5)},4870);
        setTimeout(function() {playAudio(b4)},5210);
        setTimeout(function() {playAudio(g4b)},5210);
        setTimeout(function() {playAudio(b5)},5560);
        setTimeout(function() {playAudio(d4)},5560);
        setTimeout(function() {playAudio(c6)},5730);
        setTimeout(function() {playAudio(d6)},5910);
        setTimeout(function() {playAudio(a4)},5910);
        setTimeout(function() {playAudio(f4)},5910);
        setTimeout(function() {playAudio(d6a)},6260);
        setTimeout(function() {playAudio(d4)},6260);
        setTimeout(function() {playAudio(a4)},6600);
        setTimeout(function() {playAudio(f4)},6600);
        setTimeout(function() {playAudio(d6)},6600);
        setTimeout(function() {playAudio(e6)},6950);
        setTimeout(function() {playAudio(c4)},6950);
        setTimeout(function() {playAudio(d6a)},7130);
        setTimeout(function() {playAudio(a4)},7300);
        setTimeout(function() {playAudio(f4)},7300);
        setTimeout(function() {playAudio(c6)},7300);
        setTimeout(function() {playAudio(b5)},7470);
        setTimeout(function() {playAudio(c6)},7650);
        setTimeout(function() {playAudio(a3)},7650);
        setTimeout(function() {playAudio(a4)},8000);
        setTimeout(function() {playAudio(f4)},8000);
        setTimeout(function() {playAudio(b5)},8340);
        setTimeout(function() {playAudio(f3)},8340);
        setTimeout(function() {playAudio(a5)},8520);
        setTimeout(function() {playAudio(a5a)},8690);
        setTimeout(function() {playAudio(a4)},8690);
        setTimeout(function() {playAudio(f4)},8690);
        setTimeout(function() {playAudio(g5b)},8870);
        setTimeout(function() {playAudio(g5ba)},9040);
        setTimeout(function() {playAudio(d4)},9040);
        setTimeout(function() {playAudio(f5)},9210);
        setTimeout(function() {playAudio(f5a)},9390);
        setTimeout(function() {playAudio(a4)},9390);
        setTimeout(function() {playAudio(f4)},9390);
        setTimeout(function() {playAudio(e5)},9560);
        setTimeout(function() {playAudio(e5a)},9730);
        setTimeout(function() {playAudio(e4)},9730);
        setTimeout(function() {playAudio(b4)},10080);
        setTimeout(function() {playAudio(g4b)},10080);
        setTimeout(function() {playAudio(e4)},10430);
        setTimeout(function() {playAudio(b4)},10780);
        setTimeout(function() {playAudio(g4b)},10780);
        setTimeout(function() {playAudio(g5b)},11130);
        setTimeout(function() {playAudio(e4)},11130);
        setTimeout(function() {playAudio(a5)},11300);
        //
        setTimeout(function() {playAudio(b4)},11470);
        setTimeout(function() {playAudio(g4b)},11470);
        setTimeout(function() {playAudio(b5)},11470);
        setTimeout(function() {playAudio(b5a)},11820);
        setTimeout(function() {playAudio(e4)},11820);
        setTimeout(function() {playAudio(b5)},12170);
        setTimeout(function() {playAudio(b4)},12170);
        setTimeout(function() {playAudio(g4b)},12170);
        setTimeout(function() {playAudio(a5)},12520);
        setTimeout(function() {playAudio(d4)},12520);
        setTimeout(function() {playAudio(g5b)},12690);
        setTimeout(function() {playAudio(f5)},12870);
        setTimeout(function() {playAudio(b4)},12870);
        setTimeout(function() {playAudio(g4b)},12870);
        setTimeout(function() {playAudio(e5)},13040);
        setTimeout(function() {playAudio(e5a)},13210);
        setTimeout(function() {playAudio(e4)},13210);
        setTimeout(function() {playAudio(b4)},13560);
        setTimeout(function() {playAudio(g4b)},13560);
        setTimeout(function() {playAudio(e4)},13910);
        setTimeout(function() {playAudio(g5b)},13910);
        setTimeout(function() {playAudio(a5)},14080);
        setTimeout(function() {playAudio(b4)},14260);
        setTimeout(function() {playAudio(g4b)},14260);
        setTimeout(function() {playAudio(b5)},14260);
        setTimeout(function() {playAudio(b5a)},14600);
        setTimeout(function() {playAudio(e4)},14600);
        setTimeout(function() {playAudio(b5)},14950);
        setTimeout(function() {playAudio(b4)},14950);
        setTimeout(function() {playAudio(g4b)},14950);
        setTimeout(function() {playAudio(a5)},15300);
        setTimeout(function() {playAudio(d4)},15300);
        setTimeout(function() {playAudio(g5b)},15470);
        setTimeout(function() {playAudio(f5)},15650);
        setTimeout(function() {playAudio(b4)},15650);
        setTimeout(function() {playAudio(g4b)},15650);
        setTimeout(function() {playAudio(e5)},15820);
        setTimeout(function() {playAudio(e4)},16000);
        setTimeout(function() {playAudio(e5a)},16000);
        setTimeout(function() {playAudio(b4)},16340);
        setTimeout(function() {playAudio(g4b)},16340);
        setTimeout(function() {playAudio(b5)},16690);
        setTimeout(function() {playAudio(d4)},16690);
        setTimeout(function() {playAudio(c6)},16870);
        setTimeout(function() {playAudio(d6)},17040);
        setTimeout(function() {playAudio(a4)},17040);
        setTimeout(function() {playAudio(f4)},17040);
        setTimeout(function() {playAudio(d6a)},17390);
        setTimeout(function() {playAudio(d4)},17390);
        setTimeout(function() {playAudio(a4)},17730);
        setTimeout(function() {playAudio(f4)},17730);
        setTimeout(function() {playAudio(d6)},17730);
        setTimeout(function() {playAudio(e6)},18080);
        setTimeout(function() {playAudio(c4)},18080);
        setTimeout(function() {playAudio(d6a)},18260);
        setTimeout(function() {playAudio(a4)},18430);
        setTimeout(function() {playAudio(f4)},18430);
        setTimeout(function() {playAudio(c6)},18430);
        setTimeout(function() {playAudio(b5)},18600);
        setTimeout(function() {playAudio(c6)},18780);
        setTimeout(function() {playAudio(a3)},18780);
        setTimeout(function() {playAudio(a4)},19130);
        setTimeout(function() {playAudio(f4)},19130);
        setTimeout(function() {playAudio(b5)},19470);
        setTimeout(function() {playAudio(f3)},19470);
        setTimeout(function() {playAudio(a5)},19650);
        setTimeout(function() {playAudio(a5a)},19820);
        setTimeout(function() {playAudio(a4)},19820);
        setTimeout(function() {playAudio(f4)},19820);
        setTimeout(function() {playAudio(g5b)},20000);
        setTimeout(function() {playAudio(g5ba)},20170);
        setTimeout(function() {playAudio(d4)},20170);
        setTimeout(function() {playAudio(f5)},20340);
        setTimeout(function() {playAudio(f5a)},20520);
        setTimeout(function() {playAudio(a4)},20520);
        setTimeout(function() {playAudio(f4)},20520);
        setTimeout(function() {playAudio(e5)},20690);
        setTimeout(function() {playAudio(e5a)},20870);
        setTimeout(function() {playAudio(e4)},20870);
        setTimeout(function() {playAudio(b4)},21210);
        setTimeout(function() {playAudio(g4b)},21210);
        setTimeout(function() {playAudio(e4)},21560);
        setTimeout(function() {playAudio(b4)},21910);
        setTimeout(function() {playAudio(g4b)},21910);
        //
        setTimeout(function() {playAudio(a5)},22260);
        setTimeout(function() {playAudio(e4)},22260);
        setTimeout(function() {playAudio(c5)},22600);
        setTimeout(function() {playAudio(a4)},22600);
        setTimeout(function() {playAudio(e4)},22950);
        setTimeout(function() {playAudio(a5a)},23300);
        setTimeout(function() {playAudio(c5)},23300);
        setTimeout(function() {playAudio(a4)},23300);
        setTimeout(function() {playAudio(d6)},23650);
        setTimeout(function() {playAudio(d4)},23650);
        setTimeout(function() {playAudio(c6)},23820);
        setTimeout(function() {playAudio(a4)},24000);
        setTimeout(function() {playAudio(f4)},24000);
        setTimeout(function() {playAudio(b5)},24340);
        setTimeout(function() {playAudio(b3)},24340);
        setTimeout(function() {playAudio(a5)},24520);
        setTimeout(function() {playAudio(a4)},24690);
        setTimeout(function() {playAudio(f4)},24690);
        setTimeout(function() {playAudio(g5b)},24870);
        setTimeout(function() {playAudio(a5)},25040);
        setTimeout(function() {playAudio(e4)},25040);
        setTimeout(function() {playAudio(c5)},25390);
        setTimeout(function() {playAudio(a4)},25390);
        setTimeout(function() {playAudio(e4)},25730);
        setTimeout(function() {playAudio(c5)},26080);
        setTimeout(function() {playAudio(a4)},26080);
        setTimeout(function() {playAudio(e6)},26430);
        setTimeout(function() {playAudio(e5)},26430);
        setTimeout(function() {playAudio(e4)},26430);
        setTimeout(function() {playAudio(d6)},26780);
        setTimeout(function() {playAudio(d5)},26780);
        setTimeout(function() {playAudio(d4)},26780);
        setTimeout(function() {playAudio(c6)},27130);
        setTimeout(function() {playAudio(c5)},27130);
        setTimeout(function() {playAudio(c4)},27130);
        setTimeout(function() {playAudio(b5)},27470);
        setTimeout(function() {playAudio(b4)},27470);
        setTimeout(function() {playAudio(b3)},27470);
        setTimeout(function() {playAudio(a5)},27820);
        setTimeout(function() {playAudio(e4)},27820);
        setTimeout(function() {playAudio(c5)},28170);
        setTimeout(function() {playAudio(a4)},28170);
        setTimeout(function() {playAudio(e4)},28520);
        setTimeout(function() {playAudio(a5)},28870);
        setTimeout(function() {playAudio(c5)},28870);
        setTimeout(function() {playAudio(a4)},28870);
        setTimeout(function() {playAudio(d6)},29210);
        setTimeout(function() {playAudio(d4)},29210);
        setTimeout(function() {playAudio(c6)},29390);
        setTimeout(function() {playAudio(a4)},29560);
        setTimeout(function() {playAudio(f4)},29560);
        setTimeout(function() {playAudio(b5)},29910);
        setTimeout(function() {playAudio(d4)},29910);
        setTimeout(function() {playAudio(a5)},30080);
        setTimeout(function() {playAudio(a4)},30260);
        setTimeout(function() {playAudio(f4)},30260);
        setTimeout(function() {playAudio(g5b)},30430);
        setTimeout(function() {playAudio(e4)},30600);
        setTimeout(function() {playAudio(a5)},30600);
        setTimeout(function() {playAudio(c5)},30950);
        setTimeout(function() {playAudio(a4)},30950);
        setTimeout(function() {playAudio(e4)},31300);
        setTimeout(function() {playAudio(c5)},31650);
        setTimeout(function() {playAudio(a4)},31650);
        setTimeout(function() {playAudio(a5)},32000);
        setTimeout(function() {playAudio(a4a)},32000);
        setTimeout(function() {playAudio(a3)},32000);
        setTimeout(function() {playAudio(b5)},32340);
        setTimeout(function() {playAudio(b4)},32340);
        setTimeout(function() {playAudio(b3)},32340);
        setTimeout(function() {playAudio(c6)},32690);
        setTimeout(function() {playAudio(c5)},32690);
        setTimeout(function() {playAudio(c4)},32690);
        setTimeout(function() {playAudio(d6)},33040);
        setTimeout(function() {playAudio(d5)},33040);
        setTimeout(function() {playAudio(d4)},33040);
        setTimeout(function() {playAudio(f5)},33390);
        setTimeout(function() {playAudio(c4)},33390);
        setTimeout(function() {playAudio(a4)},33730);
        setTimeout(function() {playAudio(f4)},33730);
        setTimeout(function() {playAudio(c4)},34080);
        setTimeout(function() {playAudio(a4)},34430);
        setTimeout(function() {playAudio(f4)},34430);
        setTimeout(function() {playAudio(a3)},34780);
        setTimeout(function() {playAudio(b5)},34780);
        setTimeout(function() {playAudio(a5)},35130);
        setTimeout(function() {playAudio(a4)},35130);
        setTimeout(function() {playAudio(f4)},35130);
        setTimeout(function() {playAudio(g5b)},35470);
        setTimeout(function() {playAudio(c4)},35470);
        setTimeout(function() {playAudio(f5)},35820);
        setTimeout(function() {playAudio(a4)},35820);
        setTimeout(function() {playAudio(f4)},35820);
        setTimeout(function() {playAudio(e5)},36000);
        setTimeout(function() {playAudio(f5a)},36170);
        setTimeout(function() {playAudio(d4)},36170);
        setTimeout(function() {playAudio(a4)},36520);
        setTimeout(function() {playAudio(f4)},36520);
        setTimeout(function() {playAudio(d4)},36870);
        setTimeout(function() {playAudio(a4)},37210);
        setTimeout(function() {playAudio(f4)},37210);
        setTimeout(function() {playAudio(d4)},37560);
        setTimeout(function() {playAudio(a4)},37910);
        setTimeout(function() {playAudio(f4)},37910);
        setTimeout(function() {playAudio(d4)},38260);
        setTimeout(function() {playAudio(a4)},38600);
        setTimeout(function() {playAudio(f4)},38600);
        setTimeout(function() {playAudio(e5)},38950);
        setTimeout(function() {playAudio(e4)},38950);
        setTimeout(function() {playAudio(b4)},39300);
        setTimeout(function() {playAudio(g4b)},39300);
        setTimeout(function() {playAudio(e4)},39650);
        setTimeout(function() {playAudio(e5)},40000);
        setTimeout(function() {playAudio(b4)},40000);
        setTimeout(function() {playAudio(g4b)},40000);
        setTimeout(function() {playAudio(b5)},40340);
        setTimeout(function() {playAudio(g3b)},40340);
        setTimeout(function() {playAudio(a5)},40520);
        setTimeout(function() {playAudio(b4)},40690);
        setTimeout(function() {playAudio(g4b)},40690);
        setTimeout(function() {playAudio(b3)},41040);
        setTimeout(function() {playAudio(g5b)},41040);
        setTimeout(function() {playAudio(f5)},41210);
        setTimeout(function() {playAudio(b4)},41390);
        setTimeout(function() {playAudio(g4b)},41390);
        setTimeout(function() {playAudio(e5)},41560);
        setTimeout(function() {playAudio(e5a)},41730);
        setTimeout(function() {playAudio(e4)},41730);
        setTimeout(function() {playAudio(b4)},42080);
        setTimeout(function() {playAudio(g4b)},42080);
        setTimeout(function() {playAudio(e4)},42430);
        setTimeout(function() {playAudio(b4)},42780);
        setTimeout(function() {playAudio(g4b)},42780);
        setTimeout(function() {playAudio(e4)},43130);
        setTimeout(function() {playAudio(b4)},43470);
        setTimeout(function() {playAudio(g4b)},43470);
        setTimeout(function() {playAudio(e4)},43820);
        setTimeout(function() {playAudio(b4)},44170);
        setTimeout(function() {playAudio(g4b)},44170);

        }
        function magusa(){
          var half=315;
          var full=630;
          playAudio(a4);
          setTimeout(function() {playAudio(b5)},full);
          setTimeout(function() {playAudio(c6)},full+half);
          setTimeout(function() {playAudio(a5)},full*2);
          setTimeout(function() {playAudio(a4)},full*2);
          setTimeout(function() {playAudio(c6)},full*3);
          setTimeout(function() {playAudio(b5)},full*4);
          setTimeout(function() {playAudio(g4)},full*4);
          setTimeout(function() {playAudio(b5a)},full*5);
          setTimeout(function() {playAudio(c6)},full*5+half);
          setTimeout(function() {playAudio(a5)},full*6);
          setTimeout(function() {playAudio(g4)},full*6);
          setTimeout(function() {playAudio(b5)},full*6+half);
          setTimeout(function() {playAudio(g5)},full*7);
          setTimeout(function() {playAudio(g4)},full*8);
          setTimeout(function() {playAudio(g5)},full*9);
          setTimeout(function() {playAudio(g5a)},full*9+half);
          setTimeout(function() {playAudio(g5)},full*10);
          setTimeout(function() {playAudio(f4)},full*10);
          setTimeout(function() {playAudio(a5)},full*10+half);
          setTimeout(function() {playAudio(f5)},full*11);
          setTimeout(function() {playAudio(e5a)},full*11+half);
          setTimeout(function() {playAudio(e4)},full*12);
          setTimeout(function() {playAudio(e5)},full*12);
          setTimeout(function() {playAudio(f5)},full*12+half);
          setTimeout(function() {playAudio(g5)},full*13);
          setTimeout(function() {playAudio(a5)},full*13+half);
          setTimeout(function() {playAudio(b5)},full*14);
          setTimeout(function() {playAudio(g4)},full*14);
          setTimeout(function() {playAudio(a5)},full*14+half);
          setTimeout(function() {playAudio(b5)},full*15);
          setTimeout(function() {playAudio(d6)},full*15+half);
          setTimeout(function() {playAudio(c6)},full*16);
          setTimeout(function() {playAudio(c5)},full*16);
          setTimeout(function() {playAudio(b5)},full*17);
          setTimeout(function() {playAudio(c6a)},full*17+half);
          setTimeout(function() {playAudio(c6)},full*18);
          setTimeout(function() {playAudio(a4)},full*18);
          setTimeout(function() {playAudio(a5)},full*19);
          setTimeout(function() {playAudio(c6)},full*19+half);
          setTimeout(function() {playAudio(b5)},full*20);
          setTimeout(function() {playAudio(g4)},full*20);
          setTimeout(function() {playAudio(b5a)},full*21);
          setTimeout(function() {playAudio(c6)},full*21+half);
          setTimeout(function() {playAudio(a5)},full*22);
          setTimeout(function() {playAudio(g4)},full*22);
          setTimeout(function() {playAudio(b5)},full*22+half);
          setTimeout(function() {playAudio(g5)},full*23);
          setTimeout(function() {playAudio(g4)},full*24);
          setTimeout(function() {playAudio(g5)},full*25);
          setTimeout(function() {playAudio(g5a)},full*25+half);
          setTimeout(function() {playAudio(g5)},full*26);
          setTimeout(function() {playAudio(f4)},full*26);
          setTimeout(function() {playAudio(a5)},full*26+half);
          setTimeout(function() {playAudio(f5)},full*27);
          setTimeout(function() {playAudio(e5)},full*27+half);
          setTimeout(function() {playAudio(e5a)},full*28);
          setTimeout(function() {playAudio(e4)},full*28);
          setTimeout(function() {playAudio(b4)},full*30);
          setTimeout(function() {playAudio(e4)},full*31);
          setTimeout(function() {playAudio(e4)},full*32);
          setTimeout(function() {playAudio(e5)},full*33);
          setTimeout(function() {playAudio(f5)},full*33+half);
          setTimeout(function() {playAudio(g5)},full*34);
          setTimeout(function() {playAudio(e4)},full*34);
          setTimeout(function() {playAudio(g5a)},full*34+half);
          setTimeout(function() {playAudio(a5)},full*36);
          setTimeout(function() {playAudio(g4)},full*36);
          setTimeout(function() {playAudio(g5)},full*36+half);
          setTimeout(function() {playAudio(a5)},full*37);
          setTimeout(function() {playAudio(b5)},full*37+half);
          setTimeout(function() {playAudio(g5)},full*38);
          setTimeout(function() {playAudio(g4)},full*38);
          setTimeout(function() {playAudio(a4)},full*40);
          setTimeout(function() {playAudio(b5)},full*41);
          setTimeout(function() {playAudio(c6)},full*41+half);
          setTimeout(function() {playAudio(c6a)},full*42); 
          setTimeout(function() {playAudio(a4)},full*42);
          setTimeout(function() {playAudio(a5)},full*43);
          setTimeout(function() {playAudio(c6)},full*43+half);
          setTimeout(function() {playAudio(b5)},full*44);
          setTimeout(function() {playAudio(g4)},full*44);
          setTimeout(function() {playAudio(b5a)},full*45);
          setTimeout(function() {playAudio(c6)},full*45+half);
          setTimeout(function() {playAudio(a5)},full*46);
          setTimeout(function() {playAudio(g4)},full*46);
          setTimeout(function() {playAudio(b5)},full*46+half);
          setTimeout(function() {playAudio(g5)},full*47);
          setTimeout(function() {playAudio(e4)},full*48);
          setTimeout(function() {playAudio(e5)},full*49);
          
          setTimeout(function() {playAudio(f5)},full*49+half);
          setTimeout(function() {playAudio(g5a)},full*50);
          setTimeout(function() {playAudio(e4)},full*50);
          setTimeout(function() {playAudio(g5)},full*50+half);
          setTimeout(function() {playAudio(a5)},full*52);
          setTimeout(function() {playAudio(g4)},full*52);
          setTimeout(function() {playAudio(g5)},full*52+half);
          setTimeout(function() {playAudio(a5)},full*53);
          setTimeout(function() {playAudio(b5)},full*53+half);
          setTimeout(function() {playAudio(g5)},full*54);
          setTimeout(function() {playAudio(g4)},full*54);
          setTimeout(function() {playAudio(a4)},full*56);
          setTimeout(function() {playAudio(b5)},full*57);
          setTimeout(function() {playAudio(c6a)},full*57+half);
          setTimeout(function() {playAudio(c6)},full*58);       
          setTimeout(function() {playAudio(a4)},full*58);
          setTimeout(function() {playAudio(a5)},full*59);
          setTimeout(function() {playAudio(c6)},full*59+half);
          setTimeout(function() {playAudio(b5a)},full*60);
          setTimeout(function() {playAudio(g4)},full*60);
          setTimeout(function() {playAudio(b5)},full*61);
          setTimeout(function() {playAudio(c6)},full*61+half);
          setTimeout(function() {playAudio(a5)},full*62);
          setTimeout(function() {playAudio(g4)},full*62);
          setTimeout(function() {playAudio(b5)},full*62+half);
          setTimeout(function() {playAudio(g5)},full*63);
          //
          setTimeout(function() {playAudio(a4)},full*64);
          setTimeout(function() {playAudio(b5)},full*65);
          setTimeout(function() {playAudio(c6)},full*65+half);
          setTimeout(function() {playAudio(a5)},full*66);
          setTimeout(function() {playAudio(a4)},full*66);
          setTimeout(function() {playAudio(c6)},full*67);
          setTimeout(function() {playAudio(b5)},full*68);
          setTimeout(function() {playAudio(g4)},full*68);
          setTimeout(function() {playAudio(c6)},full*69+half);
          setTimeout(function() {playAudio(a5)},full*70);
          setTimeout(function() {playAudio(g4)},full*70);
          setTimeout(function() {playAudio(b5)},full*70+half);
          setTimeout(function() {playAudio(g5)},full*71);
          setTimeout(function() {playAudio(g4)},full*72);
          setTimeout(function() {playAudio(g5)},full*73);
          setTimeout(function() {playAudio(g5a)},full*73+half); 
          setTimeout(function() {playAudio(g5)},full*74);
          setTimeout(function() {playAudio(f4)},full*74);
          setTimeout(function() {playAudio(a5)},full*74+half);
          setTimeout(function() {playAudio(f5)},full*75);
          setTimeout(function() {playAudio(e5a)},full*75+half);
          setTimeout(function() {playAudio(e5)},full*76);
          setTimeout(function() {playAudio(e4)},full*76);
          setTimeout(function() {playAudio(f5)},full*76+half);
          setTimeout(function() {playAudio(g5)},full*77);
          setTimeout(function() {playAudio(a5)},full*77+half);
          setTimeout(function() {playAudio(b5)},full*78);
          setTimeout(function() {playAudio(g4)},full*78);
          setTimeout(function() {playAudio(a5)},full*78+half);
          setTimeout(function() {playAudio(b5)},full*79);
          setTimeout(function() {playAudio(d6)},full*79+half);
          setTimeout(function() {playAudio(c6)},full*80);
          setTimeout(function() {playAudio(a4)},full*80);
          setTimeout(function() {playAudio(b5)},full*81);
          setTimeout(function() {playAudio(c6)},full*81+half);
          setTimeout(function() {playAudio(a5)},full*82);
          setTimeout(function() {playAudio(a4)},full*82);
          setTimeout(function() {playAudio(c6)},full*83);
          setTimeout(function() {playAudio(b5)},full*84);
          setTimeout(function() {playAudio(g4)},full*84);
          setTimeout(function() {playAudio(c6)},full*85+half);
          setTimeout(function() {playAudio(g4)},full*86);
          setTimeout(function() {playAudio(a5)},full*86);
          setTimeout(function() {playAudio(b5)},full*86+half);
          setTimeout(function() {playAudio(g5)},full*87);
          setTimeout(function() {playAudio(g4)},full*88);
          setTimeout(function() {playAudio(g5)},full*89);  
          setTimeout(function() {playAudio(g5a)},full*89+half);
          setTimeout(function() {playAudio(g5)},full*90);
          setTimeout(function() {playAudio(e4)},full*90);
          setTimeout(function() {playAudio(a5)},full*90+half);
          setTimeout(function() {playAudio(f5)},full*91);
          setTimeout(function() {playAudio(e5)},full*91+half);
          setTimeout(function() {playAudio(e5a)},full*92);
          setTimeout(function() {playAudio(e4)},full*92);
        }
        function playAudio(i) { 
        i.currentTime = 0;
        i.play();
        var x=i.id;
        console.log(x);
        var listing=document.getElementsByTagName("audio");
        for(var a=0; a<listing.length;a++){
          var y=listing[a].id;
          if(y==x){
            var alternative=x.slice(0,2);
            var alternativediyez=x.slice(0,3);
            if(x.slice(2)=="a")
             {
              document.getElementsByClassName(alternative)[0].style.backgroundColor="#ffab00";
             }
             else if(x.slice(3)=="a"){
              document.getElementsByClassName(alternativediyez)[0].style.backgroundColor="#ffab00";
            }
             else
             {
             document.getElementsByClassName(x)[0].style.backgroundColor="#ffab00";
             }
             setTimeout(remove,200);
            
           function remove(){
             
             if(x.slice(2)=="b"){
               document.getElementsByClassName(x)[0].style.backgroundColor="black";
             }
             else if(x.slice(2)=="a"){
              document.getElementsByClassName(alternative)[0].style.backgroundColor="#d4caca";
             }
             else if(x.slice(3)=="a"){
              document.getElementsByClassName(alternativediyez)[0].style.backgroundColor="black";
             }
             else{
             document.getElementsByClassName(x)[0].style.backgroundColor="#d4caca";
             }
            }
           }
          }
         }
        

      window.addEventListener("keydown",checkTheKey);
      function checkTheKey(key){
        switch(key.keyCode)
        {
          case 65: playAudio(c5);
          break;
          case 87: playAudio(c5b);
          break;
          case 83: playAudio(d5);
          break;
          case 69: playAudio(d5b);
          break;
          case 68: playAudio(e5);
          break;
          case 82: playAudio(f5);
          break;
          case 70: playAudio(f5b);
          break;
          case 84: playAudio(g5);
          break;
          case 71: playAudio(g5b);
          break;
          case 89: playAudio(a5);
          break;
          case 72: playAudio(a5b);
          break;
          case 85: playAudio(b5);
          break;
          case 74: playAudio(c6);
          break;
          case 73: playAudio(c6b);
          break;
          case 75: playAudio(d6);
          break;
          case 79: playAudio(d6b);
          break;
          case 76: playAudio(e6);
          break;
          case 80: playAudio(f6);
          break;
          case 186: playAudio(f6b);
          break;
          case 219: playAudio(g6);
          break;
          case 222: playAudio(g6b);
          break;
          case 221: playAudio(a6);
          break;
          case 90: playAudio(a6b);
          break;
          case 88: playAudio(b6);
          break;
        }
      }
      